main: lab3a.c
	gcc -o lab3a -g lab3a.c

clean:
	rm lab3a
	rm super.csv
	rm group.csv
	rm bitmap.csv
	rm inode.csv
	rm directory.csv
	rm indirect.csv

dist:
	tar -czvf lab3a-304627529.tar.gz lab3a.c Makefile README
